import pytest
from types import SimpleNamespace

from evidence_extractor import EvidenceExtractor
from src.agent_models import (
    ToolCall,
    LLMResponse,
)

from src.incident_agent import (
    IncidentAgent,
)

from agent_errors import (
    ToolExecutionError,
)

from src.tests.fakes import (
    FakeLLM,
    FakeFinalAnswerGenerator,
)

from src.tests.fake_tool_executor import (
    FakeToolExecutor,
)


def test_evidence_extractor_captures_pipeline_status_result():
    result = SimpleNamespace(
        structured_content={
            "found": True,
            "latest_run": {"status": "FAILED"},
        }
    )

    evidence = EvidenceExtractor().extract(
        "get_pipeline_status",
        result,
    )

    assert len(evidence) == 1
    assert evidence[0].source == "get_pipeline_status"
    assert evidence[0].category == "pipeline_status"
    assert '"status": "FAILED"' in evidence[0].summary


class FakeEvidenceExtractor:
    """
    Minimal evidence extractor for agent tests.

    The real EvidenceExtractor is not needed here 
    because these tests are tseting agent orchestration,
    not evidence-extraction logic.
    
    """

    def __init__(self):
        self.calls=[]

    def extract(
            self,
            tool_name,
            result
    ):
        self.calls.append(
            {
                "tool_name":tool_name,
                "result":result
            }
        )

        return []

class FakeMissingEvidenceDetector:
    """
    Minimal missing-evidence detector.

    The actual detector gets is own tests
    
    """

    def __init__(self):
        self.calls=[]

    def detect(self,state):
        self.calls.append(state)

        return []

class FakeContextManager:
    """
    Minimal context manager.

    For these tests we dont want context trimming
    to affect the behaviour we're testing
    
    """

    def __init__(self):
        self.calls=[]

    def trim(self,messages):
        self.calls.append(messages)

        return messages


class FakeCapabilityRegistry:
    def get_tools(self):
        return []


def create_agent(
        llm,
        tool_executor,
        final_answer_generator
):
    """
    Create an IncidentAgent with lightweight fake dependencies.
    """

    return IncidentAgent(
        mcp_client=None,
        capability_registry=FakeCapabilityRegistry(),
        tool_executor=tool_executor,
        llm=llm,
        evidence_extractor=(
            FakeEvidenceExtractor()
        ),
        missing_evidence_detector=(
            FakeMissingEvidenceDetector()
        ),
        context_manager=(
            FakeContextManager()
        ),
        final_answer_generator=(
            final_answer_generator
        )

    )

@pytest.mark.asyncio
async def test_agent_executes_requested_tool():
    """
    Verify that when the LLM requests an MCP tool,
    IncidentAgent actually executes that tool.
    
    """
    tool_call=ToolCall(
    id="call_1",
    name="get_pipeline_status",
    arguments={
        "request":{
            "pipeline_name":"customer_sync"
        }
    }
)

    llm=FakeLLM(
    [

        LLMResponse(
            content=None,
            tool_calls=[tool_call],
            assistant_message={"role": "assistant", "content": None},
        ),

        LLMResponse(
            content="Investigation complete.",
            tool_calls=[],
            assistant_message={"role": "assistant", "content": "Investigation complete."},
        )

    ]

)
    tool_executor=FakeToolExecutor(
    results={
        "get_pipeline_status":{
            "found":True,
            "pipeline":{
                "name":"customer_sync"
            },
            "latest_run":{
                "status":"FAILED"
            }
        }
    }
)
    final_answer_generator=(
    FakeFinalAnswerGenerator()
)

    agent=create_agent(
    llm=llm,
    tool_executor=tool_executor,
    final_answer_generator=final_answer_generator
)

    await agent.run(
    "customer_sync",
    "Why did customer_sync fail ?",
)

    assert len(tool_executor.calls)==1
    assert (
    tool_executor.calls[0]["tool_name"]=="get_pipeline_status"
)
    assert (
    tool_executor.calls[0]["arguments"]
    == {
        "request": {
            "pipeline_name": "customer_sync"
        }
    }
)

@pytest.mark.asyncio
async def test_agent_preserves_nested_tool_arguments():
    """
    Verify that the exact MCP tool argument strcuture
    generated by the LLM reaches the ToolExecutor.
    """

    expected_arguments={
        "request":{
            "pipeline_name":"customer_sync"
        }
    }

    tool_call=ToolCall(
        id="call_1",
        name="get_pipeline_status",
        arguments=expected_arguments,
    )

    llm = FakeLLM(
        [
            LLMResponse(
                content=None,
                tool_calls=[tool_call],
                assistant_message={"role": "assistant", "content": None},
            ),

            LLMResponse(
                content="Investigation complete.",
                tool_calls=[],
                assistant_message={"role": "assistant", "content": "Investigation complete."},
            ),
        ]
    )

    tool_executor = FakeToolExecutor(
        results={
            "get_pipeline_status": {
                "found": True,
                "pipeline": {
                    "name": "orders_pipeline"
                },
                "latest_run": {
                    "status": "FAILED"
                },
            }
        }
    )

    final_answer_generator = (
        FakeFinalAnswerGenerator()
    )

    agent = create_agent(
        llm=llm,
        tool_executor=tool_executor,
        final_answer_generator=(
            final_answer_generator
        ),
    )

    await agent.run(
        "orders_pipeline",
        "Investigate orders_pipeline."
    )

    assert (
        tool_executor.calls[0]["arguments"]
        == expected_arguments
    )

@pytest.mark.asyncio
async def test_agent_recovers_from_tool_failure():
    """
    Verify that a ToolExecutorError does not immediately 
    terminate the investigation.
    
    """

    tool_call=ToolCall(
        id="call_1",
        name="get_pipeline_logs",
        arguments={
            "request":{
                "pipeline_name":"customer_sync"
            }
        }
    )

    llm=FakeLLM(
        [
                LLMResponse(
                content=None,
                tool_calls=[tool_call],
                assistant_message={"role": "assistant", "content": None},
            ),

            LLMResponse(
                content="Investigation complete.",
                tool_calls=[],
                assistant_message={"role": "assistant", "content": "Investigation complete."},
            ),
        ]
    )

    tool_failure=ToolExecutionError(
        tool_name="get_pipeline_logs",
        message="Simulated timeout"
    )

    tool_executor=FakeToolExecutor(
        results={
            "get_pipeline_logs":tool_failure
        }
    )

    final_answer_generator = (
        FakeFinalAnswerGenerator()
    )

    agent = create_agent(
        llm=llm,
        tool_executor=tool_executor,
        final_answer_generator=(
            final_answer_generator
        ),
    )

    result=await agent.run(
        "customer_sync",
        "Investigate customer_sync"
    )

    assert final_answer_generator.called

    assert(
        result=="Final investigation report."
    )


@pytest.mark.asyncio
async def test_agent_calls_final_answer_generator():
    """
    Verify that when the LLM produces a response without
    tool calls, the agent invokes the FinalAnswerGenerator.
    """

    llm=FakeLLM(
        [
            LLMResponse(
                content="I have enough evidence",
                tool_calls=[]

            )
        ]
    )

    tool_executor=FakeToolExecutor()

    final_answer_generator=(
        FakeFinalAnswerGenerator(
            response=(
                "Structured final investigation"
            )
        )
    )

    agent=create_agent(
        llm=llm,
        tool_executor=tool_executor,
        final_answer_generator=final_answer_generator
    )

    result=await agent.run(
        "customer_sync",
        "why did customer_sync fail ?"
    )

    assert final_answer_generator.called

    assert(
        result=="Structured final investigation"
    )

    assert len(
        final_answer_generator.states
    )==1
    














