services:
  postgres:
    image: postgres:17
    container_name: incident-investigator-postgres

    environment:
      POSTGRES_DB: incident_db
      POSTGRES_USER: incident_user
      POSTGRES_PASSWORD: incident_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: